### ISSUE TITLE
ISoftDelete not behaving as expected

### ISSUE THREAD

**Issue by daz-codersoft** [steveski/Perigee.Framework#11]
If you run the AppProcessDelete in the ExampleConsoleApp (instead of the AppProces) it adds 2 people, queries, deletes one and queries again.  The second query is still returning 2 people.

I confirmed that it is setting the IsDeleted flag to true, so it’s that the query isn’t filtering.

I also tried updating to
var customersQuery = _db.Query<Customer>(true);

and this returned nothing in the first query, and 1 in the second.  So I think the logic is back-to-front (or I’ve misunderstood).  Should the “includeSoftDeleted” parameter to the Query() method return soft deleted AND not deleted entities?  Or JUST soft deleted?  I thought the former, but the latter seems to be implemented.

**Comment by steveski** [comment]
Added a private method AddIsDeletedClause(...) which takes an ISoftDelete entity and includeSoftDelete parameters applying the entity.IsDeleted == condition expression. The calling code (query and get methods) call this if TEntity is of type ISoftDelete. Non ISoftDelete records won't have this expression tacked on.

Wrote supporting integration test which confirm that after a delete no records are returned. Another test confirms that passing includeSoftDeleted = true returns the IsDeleted records.

Note that includeSoftDeleted only applied to the root entity of the Query<TEntity>() object graph and doesn't apply to all linked records. That will need to be applied in the calling query handler's where conditions.

**Comment by daz-codersoft** [comment]
Logic still not quite right.  "includeSoftDeleted" is actually implemented as "onlySoftDeleted".

I have created a test on the branch bugs/IncludeSoftDelete which demonstrates this.  The test currently fails but should pass.

**Comment by steveski** [comment]
Ah Sheeeeiittt!! Long day at work yesterday :)
Will fix tonight. Sorry about that

**Comment by daz-codersoft** [comment]
All good now!  Thanks.

**Comment by steveski** [comment]
So is softdelete AND includes now working correctly?

----
If God hadn't intended us to have a 3 martini lunch, then why do you think he put all those olive trees in the holy land?

**Comment by daz-codersoft** [comment]
I think so!  I do have a page which is supposed to actually utilise the soft delete, but I haven’t got that going yet.  But from my testing it seems like it’s working as expected now.  And yet, Include and ThenInclude is working a treat.  You can’t imagine how much easier it’s making life.

 



Darryl Hunter| Director | Codersoft Pty Ltd
Australia M: +61 (0)450 606 804 | E: darryl.hunter@codersoft.com.au <mailto:darryl.hunter@codersoft.com.au>  | W: www.codersoft.com.au <http://www.codersoft.com.au/>
